### PR TITLE
optimize: support Nacos ram role authentication

### PR DESCRIPTION
**Pull request by slievrly**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

support Nacos ram role authentication

### CODE REVIEW

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Review by funky-eyes — COMMENTED** [review]
https://github.com/apache/incubator-seata/tree/2.x/script/client
客户端是否应该补充配置示例？
Should the client side supplement the configuration examples?

**Comment by slievrly** [comment]
> https://github.com/apache/incubator-seata/tree/2.x/script/client 客户端是否应该补充配置示例？ Should the client side supplement the configuration examples?

thanks for review, I have fixed it.

**Review by funky-eyes — APPROVED** [review]
LGTM

**Pull request merged**
