### PR TITLE
optimize: validate that the primary key is free of illegal characters

### LINKED ISSUE #5136: seata1.5.2主键中带有逗号导致获取全局锁lock key值错误
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
主键中带有逗号，获取全局锁错误

### Ⅱ. Describe what happened

 seata日志:

```
09:43:43.268  INFO --- [verHandlerThread_1_33_500] i.s.s.coordinator.DefaultCoordinator     : Begin new global transaction applicationId: mom-mes-nei-biz,transactionServiceGroup: mom_tx_group, transactionName: generateNextValuesCommitImmediately(com.foreverwin.mom.mes.nei.horizon.business.common.dto.GenerateNextNumberRequest),timeout:60000,xid:192.168.5.101:8091:4846209188163301399
09:43:43.290  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.5.101:8091:4846209188163301399,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_next_number:NextNumberBO:KS,D01
,clientIp:127.0.0.1,vgroup:mom_tx_group
09:43:43.320  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.5.101:8091:4846209188163301399,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_next_number:NextNumberBO:KS,D01
,clientIp:127.0.0.1,vgroup:mom_tx_group
09:43:43.320  INFO --- [verHandlerThread_1_35_500] i.seata.server.coordinator.AbstractCore  : Register branch successfully, xid = 192.168.5.101:8091:4846209188163301399, branchId = 4846209188163301400, resourceId = jdbc:mysql://mom-mysql:3306/momx_mes ,lockKeys = z_next_number:NextNumberBO:KS,D01
09:43:43.340  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.5.101:8091:4846209188163301399,extraData=null
,clientIp:127.0.0.1,vgroup:mom_tx_group
09:43:43.358  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.5.101:8091:4846209188163301396,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_sfc_production:SfcProductionBO:KS,SJA122208A01P1
,clientIp:127.0.0.1,vgroup:mom_tx_group
09:43:43.358  INFO --- [verHandlerThread_1_37_500] io.seata.core.lock.AbstractLocker        : Global lock on [z_sfc_production:SfcProductionBO:KS] is holding by 4846209188163301386
09:43:43.360  INFO --- [verHandlerThread_1_37_500] i.s.c.e.AbstractExceptionHandler         : this request cannot acquire global lock, you can let Seata retry by setting config [client.rm.lock.retryPolicyBranchRollbackOnConflict] = false or manually retry by yourself. request: xid=192.168.5.101:8091:4846209188163301396,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_sfc_production:SfcProductionBO:KS,SJA122208A01P1
09:43:43.389  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.5.101:8091:4846209188163301396,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_sfc_production:SfcProductionBO:KS,SJA122208A01P1
,clientIp:127.0.0.1,vgroup:mom_tx_group
09:43:43.389  INFO --- [verHandlerThread_1_38_500] io.seata.core.lock.AbstractLocker        : Global lock on [z_sfc_production:SfcProductionBO:KS] is holding by 4846209188163301386
09:43:43.391  INFO --- [verHandlerThread_1_38_500] i.s.c.e.AbstractExceptionHandler         : this request cannot acquire global lock, you can let Seata retry by setting config [client.rm.lock.retryPolicyBranchRollbackOnConflict] = false or manually retry by yourself. request: xid=192.168.5.101:8091:4846209188163301396,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_sfc_production:SfcProductionBO:KS,SJA122208A01P1
09:43:43.417  INFO --- [verHandlerThread_1_39_500] io.seata.core.lock.AbstractLocker        : Global lock on [z_sfc_production:SfcProductionBO:KS] is holding by 4846209188163301386
09:43:43.416  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.5.101:8091:4846209188163301396,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_sfc_production:SfcProductionBO:KS,SJA122208A01P1
,clientIp:127.0.0.1,vgroup:mom_tx_group
09:43:43.417  INFO --- [verHandlerThread_1_39_500] i.s.c.e.AbstractExceptionHandler         : this request cannot acquire global lock, you can let Seata retry by setting config [client.rm.lock.retryPolicyBranchRollbackOnConflict] = false or manually retry by yourself. request: xid=192.168.5.101:8091:4846209188163301396,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_sfc_production:SfcProductionBO:KS,SJA122208A01P1
09:43:43.455  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.5.101:8091:4846209188163301396,branchType=AT,resourceId=jdbc:mysql://mom-mysql:3306/momx_mes,lockKey=z_sfc_production:SfcProductionBO:KS,SJA122208A01P1
,clientIp:127.0.0.1,vgroup:mom_tx_group
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS : windows
- Others:

### PR DESCRIPTION
**Pull request by ggbocoder**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
validate that the primary key is free of ","
fixes: #5136

### CODE REVIEW

**Review by funky-eyes — COMMENTED** [review]
Please add changelog.

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Review by funky-eyes — APPROVED** [review]
LGTM

**Review by slievrly — COMMENTED** [review]
LGTM

**Pull request merged**
