### PR TITLE
bugfix:fix error while the "context" is key word in DM8 when delete undolog

### LINKED ISSUE #7009: error occurs when delete undolog in 2.2.0 with DM8 DB
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
using DM8 
when upgrade from 2.1.0 to 2.2.0，an error occured
maven like below:
```
    <dependency>
      <groupId>org.apache.seata</groupId>
      <artifactId>seata-spring-boot-starter</artifactId>
      <version>2.1.0</version>
    </dependency>
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2024-11-18T14:26:06.307+08:00 ERROR 317292 --- [consumer] [h_RMROLE_1_2_32] o.a.s.rm.datasource.DataSourceManager    : branchRollback failed. branchType:[AT], xid:[10.0.7.195:8091:477967410643387686], branchId:[477967410643387689], resourceId:[jdbc:dm://192.168.8.31:5237/TEST], applicationData:[null]. reason:[Branch session rollback failed and try again later xid = 10.0.7.195:8091:477967410643387686 branchId = 477967410643387689 第 1 行, 第 27 列[context]附近出现错误: 
语法分析出错]
2024-11-18T14:26:06.308+08:00  INFO 317292 --- [consumer] [h_RMROLE_1_2_32] org.apache.seata.rm.AbstractRMHandler    : Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable

```

it always retry and never stop 

### Ⅲ. Describe what you expected to happen
debug and find the code is added in 2.2.0
image
the DELETE_SUB_UNDO_LOG_SQL is 
```
DELETE FROM undo_log WHERE context = ? AND xid = ?
```
while the **context** is key word in DM8
it should be **CONTEXT**

### PR DESCRIPTION
**Pull request by whaon**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
fix error while the "context" is key word in DM8 when delete undolog

### Ⅱ. Does this pull request fix one issue?

fixes #7009

### CODE REVIEW

**Review by funky-eyes — COMMENTED** [review]
请登记pr和作者信息至changes文件夹中的中英两版2.x.md中
Please register the PR and author information into the Chinese and English versions of the 2.x.md file located in the changes folder.

**Comment by whaon** [comment]
> 请登记pr和作者信息至changes文件夹中的中英两版2.x.md中 Please register the PR and author information into the Chinese and English versions of the 2.x.md file located in the changes folder.

done

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by funky-eyes** [comment]
请把你的钉钉号发送至我的邮箱，我将邀请你加入seata社区开发者群中。
Please send your DingTalk ID to my email, and I will invite you to join the Seata community developer group
`jianbin@apache.org`

**Pull request merged**
