### PR TITLE
optimize: expand unit test coverage for the [rocketmq] module.

### LINKED ISSUE #6506: task: Improve the test case coverage of [rocketmq] module to 70%
## Why you need it?
 Is your feature request related to a problem? Please describe in details

The test case coverage of [rocketmq] module is 30.61%, We need to go up to 70% to improve the robustness and stability of our code.
[rocketmq]模块的测试用例覆盖率为30.61%，我们需要提高到70%，以提高代码的健壮性和稳定性。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information

You can get some help from:
https://seata.apache.org/docs/developers/contributor-guide/test-coverage-guide_dev
https://seata.apache.org/blog/how-to-write-unit-tests

### PR DESCRIPTION
**Pull request by psxjoy**
- [x] I have registered the PR [changes](../changes).
- [x] I have optimized the code using seata-codestyle.xml.
- [x] I have checked all codes using seata-checkstyle.xml.

### Ⅰ. Describe what this PR did
Add unit test cases to complete the unit testing objectives for the `seata-rocketmq` module.
增加单元测试用例，完成 rocketmq模块的单元测试目标

| |Instructions	Cov.|Branches	Cov.|Missed|Cxty|Missed|Lines|Missed|Methods|Missed|Classes|
|----|----|----|----|----|----|----|----|----|----|----|
|Before|31%|8%|27|40|67|98|10|22|0|4|
|***After***|***95%***|***83%***|8|41|5|101|2|23|0|4|

### Ⅱ. Does this pull request fix one issue?

fix #6506 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Not applicable.
不适用

### Ⅳ. Describe how to verify it
Run `mvn clean test`

### Ⅴ. Special notes for reviews
In the `SeataMQProducer` class, there's a method `doSendMessageInTransaction`, which calls the parent class method `send(Message msg, long timeout)`. Since Mockito can't mock certain parent methods, the functionality has been refactored to ensure the unit test coverage exceeds 70%. The changes are as follows:

`SeataMQProducer`类中有个函数`doSendMessageInTransaction`，里面调用了父类的函数 `send(Message msg, long timeout)`。
因为Mockit 无法模拟父类的某些方法，为了单元测试用例覆盖率达到70%以上，进行了拆分。具体的修改为：

#### Before
```JAVA
public SendResult doSendMessageInTransaction(final Message msg, long timeout, String xid, long branchId)
	throws MQClientException {
	//...
	try {
		sendResult = super.send(msg, timeout);
	} catch (Exception e) {
		throw new MQClientException("send message Exception", e);
	}
	//...
}
```
#### After
```JAVA
public SendResult doSendMessageInTransaction(final Message msg, long timeout, String xid, long branchId)
	throws MQClientException {
	//...
	try {
		sendResult = superSend(msg, timeout);
	} catch (Exception e) {
		throw new MQClientException("send message Exception", e);
	}
	//...
}
public SendResult superSend(Message msg, long timeout)
	throws MQClientException, MQBrokerException, RemotingException, InterruptedException {
	return super.send(msg, timeout);
}
```

### CODE REVIEW

**Review by xingfudeshi — APPROVED** [review]
Great job!

**Comment by xingfudeshi** [comment]
Suggest placing this PR in the test section of the change log for better classification.

**Comment by psxjoy** [comment]
> Suggest placing this PR in the test section of the change log for better classification.

I appreciate your suggestion. I have already updated the PR.

**Comment by lovepoem** [comment]
LGTM

**Pull request merged**
