### PR TITLE
optimize: fix some typos in project

### PR DESCRIPTION
**Pull request by psxjoy**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
When I downloaded the src code, I found some typos in the project.
I think it should be a great opportunity to join seata's contributing journey.

### Ⅱ. Does this pull request fix one issue?

Not applicable

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Only including typos fix.

### Ⅳ. Describe how to verify it
Not applicable

### CODE REVIEW

**Review by slievrly — APPROVED** [review]
LGTM

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Comment by xingfudeshi** [comment]
@psxjoy Pleasse add this PR to change log here https://github.com/apache/incubator-seata/tree/2.x/changes

**Comment by psxjoy** [comment]
@xingfudeshi Thanks for your notice. 
I have already added this PR's info into change log.

**Review by funky-eyes — APPROVED** [review]
LGTM

**Pull request merged**
