### PR TITLE
optimize:unifty the git information

### LINKED ISSUE #6270: The git information is inconsistent
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I noticed that there are currently two places in the seata code that contain git information, one in the jar and one in the docker image. However, the git information in these two places is not unified at present. Next, I will submit a PR to unify them. The git information can help users locate problematic release versions.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by xingfudeshi**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
This PR will unify the git information.Also fixed the problem in #6264 .
```
docker image inspect docker.io/seataio/seata-server:latest
```
image

### Ⅱ. Does this pull request fix one issue?

fixes #6270

### CODE REVIEW

**Review by slievrly — COMMENTED** [review]
Can it solve the previous issue?

**Comment by slievrly** [comment]
#6263

**Comment by xingfudeshi** [comment]
> Can it solve the previous issue?

Yes.

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
