### PR TITLE
bugfix: asf config file format error

### PR DESCRIPTION
**Pull request by AlbumenJ**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

Update format according to https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=git+-+.asf.yaml+features

### CODE REVIEW

**Review by slievrly — APPROVED** [review]
LGTM

**Review by funky-eyes — APPROVED** [review]
LGTM

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Comment by xingfudeshi** [comment]
@AlbumenJ Please register this PR in change log

**Pull request merged**
