### PR TITLE
[WIP] feature: add antlr for oracle sqlparser

### PR DESCRIPTION
**Pull request by YechenGu**

### CODE REVIEW

**Review by l81893521 — COMMENTED** [review]
The rule in your parser script is separated by "_“ cause the problem that method generated by rule also separated by "_" and the CI failed.

**Review by l81893521 — COMMENTED** [review]
Please exclude the method generated by antlr in maven-pmd-plugin

**Comment by YechenGu** [comment]
> Please exclude the method generated by antlr in maven-pmd-plugin and seata_suppressions.xml

OK, I will try to solve it

**Comment by funky-eyes** [comment]
Due to code conflicts and age, if you are still interested in participating in the community, please resubmit this pr to the 2.x branch after resolving the conflict.
由于代码冲突以及年代久远，如果你还有兴趣参与到社区，请解决完冲突后重新请提交这份pr至2.x分支中

**Pull request closed without merging**
