### PR TITLE
optimize: add saga io.seata compatible api

### PR DESCRIPTION
**Pull request by ptyin**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
Add Saga related API to `compatible` module. The basic idea is to use wrapper pattern to wrap actual implementation (org.apache.seata). For all implementation classes, I added two methods, i.e., `wrap` **org.apache.seata** to **io.seata** and `unwrap` **org.apache.seata** from **io.seata**.

### Ⅱ. Does this pull request fix one issue?

Related to #6059

### CODE REVIEW

**Comment by xingfudeshi** [comment]
Please register this PR in CHANGES

**Comment by wt-better** [comment]
`io.seata.saga.engine.repo.StateMachineRepository` also need .

**Comment by xingfudeshi** [comment]
> `io.seata.saga.engine.repo.StateMachineRepository` also need .

I suggest merging this PR first. I will submit an SPI compatible PR later.

**Comment by ptyin** [comment]
> > `io.seata.saga.engine.repo.StateMachineRepository` also need .
> 
> I suggest merging this PR first. I will submit an SPI compatible PR later.

If so, I will suplement Saga component-level API in another PR.

**Comment by xingfudeshi** [comment]
> > > `io.seata.saga.engine.repo.StateMachineRepository` also need .
> > 
> > 
> > I suggest merging this PR first. I will submit an SPI compatible PR later.
> 
> If so, I will suplement Saga component-level API in another PR.

Ok,you can review my PR and see if there is anything else that needs to be added.

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Pull request merged**
