### PR TITLE
optimize: update the header of License

### PR DESCRIPTION
**Pull request by lightClouds917**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
update:update the header of License

### CODE REVIEW

**Review by slievrly — APPROVED** [review]
LGTM

**Review by funky-eyes — CHANGES_REQUESTED** [review]
待补充changelog
Merge after waiting for the supplementary change log

**Comment by lightClouds917** [comment]
> 待补充changelog Merge after waiting for the supplementary change log

done

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Review by funky-eyes — APPROVED** [review]
LGTM

**Pull request merged**
