### PR TITLE
optimize: send async response

### PR DESCRIPTION
**Pull request by yeoncheol-jang**
### Ⅰ. Describe what this PR did
Optimize code and error message for clarity.

### Ⅱ. Does this pull request fix one issue?
- https://github.com/apache/incubator-seata/issues/6515

### CODE REVIEW

**Comment by yeoncheol-jang** [comment]
cc. @funky-eyes @slievrly @xingfudeshi

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by YeonCheolGit** [comment]
> LGTM

Thanks for the review 🙇🏼

**Comment by YeonCheolGit** [comment]
> LGTM

If there are any issue that i could help with just let me know anytime. 
I am currently working full time job, so maybe solving issue not so fast but i could help and contriubte somthing this project 

Thanks 😄

**Comment by yeoncheol-jang** [comment]
Is there any issue to merge it??

cc. @funky-eyes @slievrly @xingfudeshi

**Comment by funky-eyes** [comment]
我将在2.2版本上合并这个pr，当前2.1版本的里程碑已经完成接近于发版，暂时不进行合并pr
I will merge this pr on version 2.2. The milestone of the current version 2.1 has been completed and is close to the release. I will not merge pr for the time being.

**Comment by yeoncheol-jang** [comment]
> 我将在2.2版本上合并这个pr，当前2.1版本的里程碑已经完成接近于发版，暂时不进行合并pr I will merge this pr on version 2.2. The milestone of the current version 2.1 has been completed and is close to the release. I will not merge pr for the time being.

I understand it. Thank you for the kind description.

**Pull request merged**
