### PR TITLE
security: upgrade some dependencies

### LINKED ISSUE #5945: [TODO] Check the dependency libs of all repositories, fix CVEs from them.
This was mentioned through the ASF incubator voting. I think it would be better if we could track it.

```
One minor nit - the dependency list in
https://cwiki.apache.org/confluence/display/INCUBATOR/Seata+Proposal
has a great deal out of outdated dependencies - with a large number of
CVEs associated with them.
```

Let's scan them and fix them soon.

### PR DESCRIPTION
**Pull request by slievrly**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
upgrade some dependencies

### Ⅱ. Does this pull request fix one issue?

fixes #5945

### CODE REVIEW

**Comment by leizhiyuan** [comment]
https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/ has not 2.5.21  version
and https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all 

This artifact was moved to:

[org.apache.groovy](https://mvnrepository.com/artifact/org.apache.groovy) » [groovy-all](https://mvnrepository.com/artifact/org.apache.groovy/groovy-all)

**Comment by slievrly** [comment]
> https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/ has not 2.5.21 version and https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all
> 
> This artifact was moved to:
> 
> [org.apache.groovy](https://mvnrepository.com/artifact/org.apache.groovy) » [groovy-all](https://mvnrepository.com/artifact/org.apache.groovy/groovy-all)

2.5.21: https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/2.5.21/

**Comment by slievrly** [comment]
https://mvnrepository.com/artifact/org.apache.groovy/groovy-all  oes not contain the 2.x version.

**Comment by slievrly** [comment]
image

fix in #5924

cherry-pick later.

**Review by slievrly — COMMENTED** [review]
DISCARD

**Pull request closed without merging**
