### PR TITLE
optimize: upgrade alibaba/druid version  to 1.2.20

### LINKED ISSUE #6522: [druid 版本升级]请问下个版本大概多久发布，依赖的druid会升级到最新版本嘛?
目前seata2.0.0使用的druid版本是1.2.7,但是这个版本的druid解析postgresql的 FETCH FIRST 1 rows only 语句会出现语法错误，druid社区已经在1.2.20+版本解决了这个问题：https://github.com/alibaba/druid/commit/e40032696e126e33b578203e382aed68de42f753
请问一下下一个seata版本大概多久升级，其中依赖的druid版本会升级到最新版本吗？

### PR DESCRIPTION
**Pull request by God-Gan**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
将 alibaba/druid的版本从1.2.7升级到1.2.20
upgrade alibaba/druid version from 1.2.7 to 1.2.20

### Ⅱ. Does this pull request fix one issue?
fixes #6522

### CODE REVIEW

**Review by funky-eyes — COMMENTED** [review]
Can you fix the issues exposed in these CI?

**Comment by God-Gan** [comment]
@funky-eyes 暂时先升级到1.2.20也能满足业务，升级到1.2.21和1.2.22遇到的CI问题我暂时不知道怎么解决:)

**Comment by God-Gan** [comment]
请问这个pr可以合入到2.1.0版本嘛 @funky-eyes

**Comment by funky-eyes** [comment]
> 请问这个pr可以合入到2.1.0版本嘛 @funky-eyes

合并至2.2

**Review by funky-eyes — APPROVED** [review]
LGTM

**Pull request merged**
