### PR TITLE
optimize: fix problem of `maven-pmd-plugin`

### LINKED ISSUE #6293: Enumeration of [Role] fields missing comment information
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Using the Packing Command： `mvn -Prelease-seata -Dmaven.test.skip=true -Dskip.npm=true  clean install -U -P arrch64 -T4C  -Dcheckstyle.skip=true`
Enumeration of [Role] fields missing comment information
image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by wangliang181230**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

bugfix: fix problem of `maven-pmd-plugin`

1. 修复PMD规范问题；
2. PMD插件的 `check` 功能，从 `verify` 阶段提前到 `validate` 阶段执行；且默认禁用该插件；
3. `build.yml` 中，启用 PMD 校验。

### Ⅱ. Does this pull request fix one issue?

fixes #6293

### CODE REVIEW

**Review by slievrly — COMMENTED** [review]
For non-transactional functional defects, please use the prefix "optimize".

**Comment by wangliang181230** [comment]
> For non-transactional functional defects, please use the prefix "optimize".

OK.

**Review by funky-eyes — APPROVED** [review]
LGTM

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
