### PR TITLE
refactor: standardize Seata Exception

### PR DESCRIPTION
**Pull request by slievrly**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

standardize Seata Exception

### CODE REVIEW

**Review by funky-eyes — COMMENTED** [review]
A test case can be added to see the specific exception logging style when ci is pipelined

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Comment by xingfudeshi** [comment]
Please resolve conflicting files

**Comment by slievrly** [comment]
> A test case can be added to see the specific exception logging style when ci is pipelined

https://github.com/apache/incubator-seata/pull/6269/files#diff-1468ca2433d8757b616ee24c5869c2628e14526552a4f5b0fba07b04aee622dbR44

**Review by funky-eyes — APPROVED** [review]
LGTM

**Pull request merged**
