### PR TITLE
bugfix: fix cache scheduled refresh issue.

### LINKED ISSUE #6660: 定时刷新TableMeta缓存的功能失效了
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
定时刷新TableMeta缓存的功能失效了，程序每900秒后会由业务调用主动查询一次tableMeta导致慢请求
1.7.0 版本之后没有定时任务发起`tableMetaRefreshEvent`事件,导致`tableMetaRefresh`会一直处于`tableMetaRefreshQueue.take()`状态。

在https://github.com/apache/incubator-seata/pull/4734/files 这次更新之后，原60秒刷新一次tablemeta缓存的功能失效了。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by wuwen5**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
Restore some code and fix cache scheduled refresh issue.

### Ⅱ. Does this pull request fix one issue?

fixes #6660

### CODE REVIEW

**Review by funky-eyes — COMMENTED** [review]
我认为应该将take改为poll，加上超时时间就可以了，不需要独立一个线程去处理这个刷新缓存时间，你觉得呢？
I think we should change "take" to "poll" and add a timeout, that should be enough. We don't need a separate thread to handle the cache refresh time. What do you think about that?

**Comment by wuwen5** [comment]
> 我认为应该将take改为poll，加上超时时间就可以了，不需要独立一个线程去处理这个刷新缓存时间，你觉得呢？ I think we should change "take" to "poll" and add a timeout, that should be enough. We don't need a separate thread to handle the cache refresh time. What do you think about that?

OK， Good idea

**Comment by wuwen5** [comment]
@funky-eyes  
已经修改，同时我将`currentTimeMillis`改为了`nanoTime`,因为计算时间流逝应该使用单调时间而不是挂钟时间，避免时钟回拨问题.

It has been modified, and at the same time, I have changed the `currentTimeMillis` to `nanoTime` because calculating the passage of time should use monotonic time instead of clock time to avoid clock back issues.

**Review by funky-eyes — APPROVED** [review]
LGTM
麻烦在changelog中找到中英两版语言的2.x.md在其中将该pr登记，并登记你的github信息

**Comment by funky-eyes** [comment]
请把你的钉钉联系方式发送至：jianbin@apache.org 我将邀请你加入seata开发者群中
Please send me your DingTalk contact information to jianbin@apache.org. I will invite you to join the Seata developers group.

**Pull request merged**
