### PR TITLE
optimize: add license header for SPI file

### PR DESCRIPTION
**Pull request by slievrly**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

add license header for SPI file

### CODE REVIEW

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by funky-eyes** [comment]
Please register the pr information.

**Comment by slievrly** [comment]
> Please register the pr information.

PR change will be added after commit cherry pick to 2.1.0.

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Pull request merged**
