### PR TITLE
optimize: fix typo

### PR DESCRIPTION
**Pull request by jbampton**
- [ ] I have registered the PR [changes](../changes).

### CODE REVIEW

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Comment by xingfudeshi** [comment]
Please register this pr in changes.

**Review by funky-eyes — APPROVED** [review]
https://github.com/apache/incubator-seata/blob/2.x/changes/zh-cn/2.x.md
https://github.com/apache/incubator-seata/blob/2.x/changes/en-us/2.x.md
请在上述md文件中登记pr信息和作者信息
Please register pr information and author information in the above md file

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
