### PR TITLE
bugfix: fix SQLServer-related SQL error when using database of SQLServer

### PR DESCRIPTION
**Pull request by TakeActionNow2019**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
1. Fix the failure of seata server's starting because of SQL error in org.apache.seata.core.store.db.sql.lock.SqlServerLockStoreSql#INSERT_LOCK_SQL_SQLSERVER when using database SQLServer;
2. Fix the failure of querying TransactionInfo and GlobalLockInfo at seata server console when using database SQLServer;
3. Adjust string constant references of database type by using existent constants of database type.

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by TakeActionNow2019** [comment]
Could anyone help me review and merge it? please!

**Comment by funky-eyes** [comment]
Do you have a dingtalk account? Please send it to my email and I will invite you to join the seata developer group
`jianbin@apache.org`

**Comment by TakeActionNow2019** [comment]
The original sql that select data from table distributed_lock for update doesn't suit SQLServer.
image

**Comment by TakeActionNow2019** [comment]
The SQL that creates table distributed_lock and inserts distributed lock constants are missed.
image

**Comment by TakeActionNow2019** [comment]
This page-query SQL doesn't suit SQLServer. 
Error will occur, ie "The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified."
Clear sort fields should be specified in subqueries here. 
image
image
image

**Comment by TakeActionNow2019** [comment]
image

**Comment by TakeActionNow2019** [comment]
Using exsiting database type constants.
image
image
image

**Comment by TakeActionNow2019** [comment]
Almost all the details have been supplemented.
Could anyone help me review and merge it? Please!
Would you like to do the favour for me? @funky-eyes  @ptyin

**Comment by funky-eyes** [comment]
Hi @TakeActionNow2019  , could you merge the first two issues and then create a separate PR for them? I prefer not to have too many unrelated commits mixed in one PR as it will make the review process more difficult.

**Pull request closed without merging**
