### PR TITLE
optimize: remove the useless file

### PR DESCRIPTION
**Pull request by lightClouds917**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
remove:the duplicate header

### CODE REVIEW

**Review by slievrly — COMMENTED** [review]
It looks like this file has been entirely commented out. I suggest we just delete it.

**Comment by lightClouds917** [comment]
> It looks like this file has been entirely commented out. I suggest we just delete it.

ok,i will delete it

**Review by funky-eyes — COMMENTED** [review]
我不理解为何要单独提pr删除该无用文件，而不是提交一份将相关测试用例完善的pr来去除这个无效文件？
I don't understand why I need to mention PR to delete this useless file separately, instead of submitting a PR that perfects the relevant test cases to remove this invalid file?

**Comment by lightClouds917** [comment]
> 我不理解为何要单独提pr删除该无用文件，而不是提交一份将相关测试用例完善的pr来去除这个无效文件？ I don't understand why I need to mention PR to delete this useless file separately, instead of submitting a PR that perfects the relevant test cases to remove this invalid file?

This pr has nothing to do with test cases ，it is intended to completely clean up the outdated license headers in the project, which is the point. After this pr, there is no “Copyright 1999-2019 Seata.io Group."

**Review by funky-eyes — APPROVED** [review]
LGTM

**Pull request merged**
